name: My-FrontEnd-Application

trigger:
 branches:
   include:
     - none

pool:
  name: SAgent

stages:
  - stage: Scan
    displayName: Scan Code
    jobs:
      - job: Scan
        steps:
          - checkout: self # Tocopy the repo into the Agent

  #         - task: Gitleaks@3
  #           inputs:
  #             scanlocation: '$(Build.SourcesDirectory)'
  #             configtype: 'default'
  #             reportformat: 'csv'
  #             reportname: 'result'

  # - stage: Build
  #   displayName: Build APP
  #   jobs:
  #     - job: Build
  #       steps:
  #         # - task: JavaToolInstaller@1
  #         #   inputs:
  #         #     versionSpec: '24'
  #         #     jdkArchitectureOption: 'x64'
  #         #     jdkSourceOption: 'PreInstalled'
          
  #         - task: NodeTool@0
  #           displayName: NodeJS Installation
  #           inputs:
  #             versionSource: 'spec'
  #             versionSpec: '24.x'

  #         - task: Npm@1
  #           displayName: NPM Validate
  #           inputs:
  #             command: 'ci' # Clean Installation-delete od ad add new
  #             workingDir: '$(System.DefaultWorkingDirectory)'

  #         - task: Npm@1
  #           displayName: Compile Application
  #           inputs:
  #             command: 'custom'
  #             workingDir: '$(System.DefaultWorkingDirectory)'
  #             customCommand: 'run build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: build
              # PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'SanjayArtifact_0104'
              publishLocation: 'Container'
              

          

