trigger:
  branches:
    include:
      - main
      - feature/sa
    exclude:
      - sanjay
      - anil

pool: SAgent

stages:
  - stage: lint
    displayName: linting
    jobs: 
      - job: Javalint
        displayName: Javalinting
        #Biom,Megalinter,Superlinterlinkse dekh lenge
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'biome lint $(System.DefaultWorkingDirectory)/src/'
          