trigger:
  branches:
    include:
      - none
      - feature/sa
    exclude:
      - sanjay
      - anil

pool: SAgent

stages:
  - stage: lint
    displayName: linting
    jobs: 
      - job: lint
        displayName: linting
        #Biom,Megalinter,Superlinterlinkse dekh lenge
        steps:
        # - task: PowerShell@2
        #   displayName: Biomelint-Java
        #   inputs:
        #     targetType: 'inline'
        #     script: 'biome lint $(System.DefaultWorkingDirectory)/src/'
        - task: Npm@1
          inputs:
            command: 'install'